# Generated by Django 3.2.9 on 2021-11-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olt', models.CharField(blank=True, max_length=30)),
                ('mac', models.CharField(blank=True, max_length=20)),
                ('epon', models.CharField(blank=True, max_length=20)),
                ('level_2021_11_02', models.CharField(blank=True, max_length=40)),
                ('level_2021_11_03', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
